import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.scss";
import "./globals.css";
import ScrollTop from "@/components/ScrollTop/ScrollTop";
import Header from '@/components/Header/page'
import Footer from '@/components/Footer/Footer'
import ShowContact from "@/components/ShowContact/ShowContact";
import LoadingProvider from "@/context/LoadingCOntext";
import PageLoadWatcher from "@/context/PageLoadWatcher";
import PromotionalBanner from "@/components/PromotionalBanner/PromotionalBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // customize as needed
  variable: '--font-poppins', // optional for CSS variable use
  display: 'swap',
});

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {/* PROTOTYPE LABEL */}
        <div
          style={{
            position: 'fixed',
            top: '25px',
            right: '45px',
            transform: 'translateX(50%) rotate(45deg)',
            background: 'red',
            color: 'white',
            padding: '6px 40px',
            fontWeight: 'bold',
            fontSize: '20px',
            zIndex: 10,
            whiteSpace: 'nowrap',
            boxShadow: '2px 2px 10px rgba(0,0,0,0.2)',
          }}
        >
          Prototype
        </div>
        <LoadingProvider>
          <PageLoadWatcher />
          <div className='mainHomeSection'>
            <Header />
            {children}
            <ShowContact />
            <Footer />
          </div>
        </LoadingProvider>

        {/* SCROLL TO TOP BUTTON */}
        <PromotionalBanner />
        <ScrollTop />
      </body>
    </html>
  );
}
